### ISSUE TITLE
当前clash自行替换文件后，配置文件仍然保持GEOIP, CN指定可用吗？

### ISSUE THREAD

**Issue by gang4399** [Hackl0us/GeoIP-CN#6]
如题，自行替换mmdb文件后，配置文件仍然是`GEOIP, CN`这么指定吗？
如果我只写GEOIP也行吧？

**Comment by Hackl0us** [comment]
这个数据库中只包括 GEOIP 是 CN 的地址段信息，所以配置文件如果是 `GEOIP, CN, DIRECT` 完全不用管，保持不变。
如果你的配置文件用了其他地区，如 `GEOIP, US, Proxy` 等，那这个地址库就不能帮到你了。
